name = "F2Algebra"
uuid = "3b98dc37-3be5-4b61-8d02-d0d0e2fa5513"
authors = ["josheligoldman <josheligoldman@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
